- name: cd to synchronised directory (/vagrant) on login
  lineinfile: dest=/home/vagrant/.bashrc regexp="^cd /vagrant$" line="cd /vagrant"

- name: setup postgres for vagrant user
  become: true
  become_user: postgres
  postgresql_user: name=vagrant role_attr_flags=SUPERUSER